### ISSUE TITLE
Having issues to understand how to use gis to Salome

### ISSUE THREAD

**Issue by RomanLF** [pprodano/pputils#13]
Hello,

I struggle to build a city model on Salome from a shapefile. I try to post here a question about your script gis2salome.

I would like to build a 2D mesh of a city footprint and extrude it building by building with their own height on salome. I would like to test a simple case first to be able to export the following shapefile to salome (in the illustration I opened it as a GeodDataFrame) :
![image](https://user-images.githubusercontent.com/74862185/162221643-ff28ac2c-c68a-4eab-ba5c-df0a2bae56e4.png)
On the image the polygon named "ext" is a polygon which fills to space to represent the ground and "batiment" are the polygons which represent the buildings.

I have executed your example and I have this figure : 
![image](https://user-images.githubusercontent.com/74862185/162222213-bfabd2b9-31e8-40c5-8060-1c4b11ad4207.png)
Is it possible to export my shapefile to the desired data of your program in a simple manner ?
And is it possible with your tool to build a geometry as I have shown on the first picture ?

Kind regards,

Roman

**Comment by pprodano** [comment]
Hello Roman, sorry for the delayed reply. Yes, you can absolutely do this. Depending on what you are wanting to do, few different ways could be considered. I tend to choose the simplest. I would try gis2mesh.py which uses Triangle to generate a mesh based on a boundary, breakline, island and area constraints. I have used this to generate very large meshes. Email me if you wish to discuss further. Cheers.

**Comment by RomanLF** [comment]
Hello "pprodano". Thank you for your answer. As you invite me to mail you, I will give you more details about my needs in an email.

Thank you a lot,
Roman
