### ISSUE TITLE
breaklines2shp.py issue with pyshp

### ISSUE THREAD

**Issue by nstrahl** [pprodano/pputils#3]
while trying to convert .csv breaklines into .shp files I ran into a problem with the pputils-included pyshp version 2.1.0, the script of which outputs the following:

for 2d shapefiles:

Traceback (most recent call last):
  File "breaklines2shp.py", line 90, in <module>
    out = Writer(shapeType=3) # this is POLYLINE type, or 2d shapefile
  File "C:\pputils-master\pyshp\shapefile.py", line 1069, in __init__
    raise Exception('Either the target filepath, or any of shp, shx, or dbf must be set to create a shapefile.')
Exception: Either the target filepath, or any of shp, shx, or dbf must be set to create a shapefile.

for 3d shapefiles:

Traceback (most recent call last):
  File "breaklines2shp.py", line 92, in <module>
    out = Writer(shapeType=13) # this is POLYLINEZ, or 3d shapefile
  File "C:\pputils-master\pyshp\shapefile.py", line 1069, in __init__
    raise Exception('Either the target filepath, or any of shp, shx, or dbf must be set to create a shapefile.')
Exception: Either the target filepath, or any of shp, shx, or dbf must be set to create a shapefile.

I noticed the breaklines2shp.py file lacked the proper input for the writer class on lines 92 and 94 so I changed the lines to include the required target parameter:
out = Writer(target=output_file, shapeType=3) #13 for 3d

After that I ammended a further portion of the code by adding an if-else statement that reads:

if (shptype == '2d'):
    out.line(lines=[part])
else:	 
    out.linez(lines=[part])

save is not a member of the writer class so I also had to change the line that reads:
#out.save(output_file) 
to:
out.close() 

after that the script was capable of outputting correct 2d and 3d .shp files

I have appended the corrected scripts along with some comments. All of these changes were made in good faith and I hope they are correct and help with the project. Other than that thumbs up to the pputils creator.

[breaklines2shp.zip](https://github.com/pprodano/pputils/files/3797393/breaklines2shp.zip)

**Comment by pprodano** [comment]
This script was broken for quite some time (after I updated to the latest version of pyshp). Thank you so much for fixing the issue. I will incorporate your changes next time I update the code. Thanks once again!
