### ISSUE TITLE
Writing 3D serafin file

### ISSUE THREAD

**Issue by biqilong** [pprodano/pputils#4]
Hi Pat,

The module selafin_io_pp.py contains a function for writing serafin file: writeHeader(). But this function currently works only with 2D serafin file. I suspect the main problem is during writing IKLE array. 

When it writes out the IKLE array, only 3 columns are included:

`self.f.write(pack('>i', 4*self.NELEM*self.NDP))`
`for i in range(self.NELEM):`
`  self.f.write(pack('>i', self.IKLE[i,0]))`
`  self.f.write(pack('>i', self.IKLE[i,1]))`
`  self.f.write(pack('>i', self.IKLE[i,2]))`
`  self.f.write(pack('>i', 4*self.NELEM*self.NDP))`

This is perfect for the 2D file. But for 3D file, it usually has 6 columns, because NDP=6. So simply modify a small part:

`self.f.write(pack('>i', 4*self.NELEM*self.NDP))`
`    for i in range(self.NELEM):`
`      for j in range(self.NDP):`
`        self.f.write(pack('>i', self.IKLE[i,j]))`
`    self.f.write(pack('>i', 4*self.NELEM*self.NDP))`

It will work for 3D file as well.

Also a small mistake at line 86:
`self.IKLE = np.zeros((self.NELEM,self.NPOIN), dtype=np.int32)`

should be I guess:
`self.IKLE = np.zeros((self.NELEM,self.NDP), dtype=np.int32)`

Best regards,
Qilong

**Comment by pprodano** [comment]
Hi Qilong,

Thank you so much for this. When I wrote the selafin writer, I only tested it for writing 2D result files. I will certainly incorporate your revision next time I update the code.

Thanks again,

Pat

**Comment by biqilong** [comment]
Glad to help! Very useful package by the way. 👍

**Comment by pprodano** [comment]
Code updated. Closing the issue.
