### ISSUE TITLE
problem with gmsh2adcirc.py

### ISSUE THREAD

**Issue by matalquier** [pprodano/pputils#5]
Hello, I'm using PPUTILS, firstable congratulations for that work and quality of the pputils's manual!! 

I have a problem with a case with scipt gmsh2adcirc.py :
**C:\opentelemac-mascaret\python27\lib\site-packages\numpy\lib\npyio.py:1361: UserWarning: genfromtxt: Empty input file: "temp_elements"
warnings.warn('genfromtxt: Empty input file: "%s"' % fname)
Traceback (most recent call last):
File "D:\pputils-master\pputils-master\gmsh2adcirc.py", line 113, in <module>
e1 = elements_data[5,:]
IndexError: index 5 is out of bounds for axis 0 with size 0**

Here is the beginning of my msh file :
_$MeshFormat
2.2 0 8
$EndMeshFormat
$Nodes
4020424_

Thank you in advance
regards.

**Comment by matalquier** [comment]
To complete my problem, here is the beginning of my mesh file :
_$MeshFormat
2.2 0 8
$EndMeshFormat
$Nodes
4020424_

**Comment by matalquier** [comment]
> Hello, I'm using PPUTILS , firstable congratulations for that work and quality of the pputils's manual!!
I have a problem with a case with scipt gmsh2adcirc.py :
> **C:\opentelemac-mascaret\python27\lib\site-packages\numpy\lib\npyio.py:1361: UserWarning: genfromtxt: Empty input file: "temp_elements" warnings.warn('genfromtxt: Empty input file: "%s"' % fname) Traceback (most recent call last): File "D:\pputils-master\pputils-master\gmsh2adcirc.py", line 113, in e1 = elements_data[5,:] IndexError: index 5 is out of bounds for axis 0 with size 0**
> 
> Here is the beginning of my msh file :
> _$MeshFormat 2.2 0 8 $EndMeshFormat $Nodes 4020424_
> 
> Thank you in advance
> regards.

**Comment by pprodano** [comment]
Hello,

You are correct that the gmsh2adcirc.py script presently works for GMSH v2 formatted files. 

First, before using it on a 4M nodes GMSH file, are you able to confirm that the gmsh2adcirc.py script works using the example files found in ./examples/gis2gmsh ? Try those first, and let me know if the script correctly creates the adcirc file.

Thanks,

Pat

**Comment by matalquier** [comment]
Yes, the gmsh2adcirc.py script works with the exemple file "example_01_holes". 

the .grd files created :
ADCIRC
2016 1057
1 218.020 382.573 0.000
2 234.644 352.522 0.000
3 238.481 348.525 0.000
4 241.518 345.169 0.000
...
2016 3 34 994 33

Do you think the script works with more than 1M points?

Thank you.

**Comment by pprodano** [comment]
Hello,

1M points shouldn't be a problem. I previously used it to convert much larger mesh (in the 40M nodes range). 

In order to debug, please attach the files here and I will take a look. Or, send me the files via email if you don't want to post them here. Please include the GMSH *.geo file from which the mesh is generated, and the *.msh file that you created.

Pat

**Comment by matalquier** [comment]
Thank you for your help, here attached files geo and msh:
[maillage_seyne3.zip](https://github.com/pprodano/pputils/files/4124386/maillage_seyne3.zip)

**Comment by pprodano** [comment]
Hello,

I loaded the files in GMSH, generated the mesh, and then exported the resulting mesh as a *.msh file. When exporting the *.msh mesh, make sure you check the box that says "Save all elements", and that the files are in ASCII version 2.2. The script worked without issue.

Pat

P.S. Given what your domain is, you have too many elements. I am sure your study would be OK with much less.

**Comment by matalquier** [comment]
OK thank you, your script works fine! My problem was in the creation of the msh file, by command line not appropriated.

Effectively my case could be optimized, thanks

**Comment by pprodano** [comment]
Glad all worked out. Closing the issue.
