### ISSUE TITLE
assigning bottom elevations to mesh

### ISSUE THREAD

**Issue by nstrahl** [pprodano/pputils#6]
Greetings,

I have made a slight modification to the assign_h script to be able to modify the bottom for a warm start. I made some channel polygons with a defined depth h and have it substracted from the slf mesh as follows:
if (variables[i].find('BOTTOM') > -1):    #
    res_ws[i,:] = np.add(bottom, -h)        #

while this all works I am not getting clean-cut channel edges in the slf file, the edges are rather blurry. The newly assigned variable seems to get interpolated. 

Is there a way to fix this? I was thinking of maybe assigning the values to the tin directly, but there seems to be no script for this.

thank you.

**Comment by pprodano** [comment]
I am having a hard time understanding what you are trying to do. Please include a picture which will illustrate your problem. Or attach your files, and I can take a look.

Try and creating polygons that encapsulate the entire mesh. That way, nothing will be left to chance.

**Comment by nstrahl** [comment]
Thanks for the reply. I simply added a minute buffer to the polygons and that worked.
